import type { NextPage } from "next";
import Head from "next/head";
import { Article, CTA, Brand, Header } from "../components";
import {
  Footer,
  Blog,
  Possibility,
  Features,
  WhatGPT3,
  Hero,
} from "../containers";
import * as S from "../styles/index.styles";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.HomeContainer>
        <div className="gradient__bg">
          <Header />
          <Hero />
        </div>
        <Brand />
        <WhatGPT3 />
        <Features />
        <Possibility />
        <CTA />
        <Blog />
        <Footer />
      </S.HomeContainer>
    </div>
  );
};

export default Home;
